name: Example Tests
on: [push, pull_request_target]
jobs:
  Example:
    name: Example
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup CLI 
      uses: jfrog/setup-jfrog-cli@v2
      env:
          JF_ARTIFACTORY_1: ${{ secrets.JF_SECRET_ENV_1 }}
    - name: Audit
      run: |
          # Audit your project
          jfrog audit
